---

ansible_tower:
  url: "https://192.168.122.81"
  admin_password: "admin01"
  projects:
  - name: "infra-ansible"
    description: "Infra Ansible"
    scm_type: "git"
    scm_url: "https://github.com/bvkin/infra-ansible.git"
    scm_branch: "atlassian-workflow"
    organization: "Default"
  - name: "omp-dynamic-inventories"
    description: "Dynamic Inventories For OMP"
    scm_type: "git"
    scm_url: "https://github.com/rht-labs/omp-dynamic-inventories.git"
    scm_branch: "master"
    organization: "Default"
  credentials:
  - name: "Atlassian Credential"
    description: "My Credential 1"
    organization: "Default"
    credential_type: "Machine"
  job_templates:
  - name: "Add Atlassian Groups/Users"
    description: "Adds groups and users to atlassian"
    inventory: "Atlassian-Test"
    credential: "Atlassian Credential"
    project: "infra-ansible"
    playbook: "playbooks/manage-users/manage-atlassian-users.yml"
  - name: "Failure Notification"
    description: "Alert SRE group if atlassian users/groups failed to populate"
    inventory: "Atlassian-Test"
    credential: "Atlassian Credential"
    project: "infra-ansible"
    playbook: "playbooks/notifications/email-notify-list-of-users.yml"
  workflow_templates:
  - name: "Atlassian Users and Groups Creation"
    nodes:
    - unified_job_template:
        name: "Add Atlassian Groups/Users"
      failure_nodes:
      - unified_job_template:
          name: "Failure Notification"
