---

- name: Refresh facts for updated docker information
  setup:

- name: Find difference in mtu between the default ipv4 and docker devices
  set_fact:
    mtu_diff: "{{ ansible_facts.default_ipv4.mtu - ansible_facts[lookup('vars','docker_network_interface')].mtu }}"

- name: Check if file has mtu set 
  command: grep -q "mtu=" /etc/sysconfig/docker-network
  register: docker_mtu_set_check
  check_mode: no
  ignore_errors: yes 
  changed_when: no

- name: Update the mtu if previously set 
  replace:
    path: /etc/sysconfig/docker-network
    regexp: '--mtu=[0-9]\d*'
    replace: "--mtu={{ ansible_facts.default_ipv4.mtu - docker_mtu_offset }}"
  when: 
  - docker_mtu_set_check.rc == 0
  notify: 
  - restart docker
  
- block:
  - name: Append mtu option
    replace:
      path: /etc/sysconfig/docker-network
      regexp: '^DOCKER_NETWORK_OPTIONS=(.*)$'
      replace: 'DOCKER_NETWORK_OPTIONS=\1 --mtu={{ ansible_facts.default_ipv4.mtu - docker_mtu_offset }}'

  - name: Format file arguments 
    replace:
      path: /etc/sysconfig/docker-network 
      regexp: "'" 
      replace: ""

  - name: Format file arguments
    replace:
      path: /etc/sysconfig/docker-network
      regexp: "^DOCKER_NETWORK_OPTIONS=(.*)"
      replace: DOCKER_NETWORK_OPTIONS='\1'
    notify: 
    - restart docker    
  when:
  - docker_mtu_set_check.rc == 1
  
