---

- name: "Initilize facts"
  set_fact:
    existing_job_templates_output: []
    existing_workflow_templates_output: []

# Utilize the `rest_get` library routine to ensure REST pagination is handled
- name: "Get the existing job templates"
  rest_get:
    host_url: "{{ ansible_tower.url | default(default_ansible_tower_url) }}"
    rest_user: "{{ ansible_tower.admin_username | default(default_ansible_tower_admin_username) }}"
    rest_password: "{{ ansible_tower.admin_password }}"
    api_uri: "/api/v2/job_templates/"
  register: existing_job_templates_output

# Utilize the `rest_get` library routine to ensure REST pagination is handled
- name: "Get the existing workflow templates"
  rest_get:
    host_url: "{{ ansible_tower.url | default(default_ansible_tower_url) }}"
    rest_user: "{{ ansible_tower.admin_username | default(default_ansible_tower_admin_username) }}"
    rest_password: "{{ ansible_tower.admin_password }}"
    api_uri: "/api/v2/workflow_job_templates/"
  register: existing_workflow_templates_output

- name: "Process the inventory workflow template"
  include_tasks: process-workflow-template.yml
  with_items:
  - "{{ ansible_tower.workflow_templates }}"
  loop_control:
    loop_var: workflow_template
